
name: Build Typst document
on: [push]
jobs:
  build_typst:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses:  Jarivanbakel/typst-action@v3
        with:
          input_files: '**.typ'
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: '**.pdf'
